### ISSUE TITLE
Overplotting pair_plots

### ISSUE THREAD

**Issue by andersdot** [arviz-devs/arviz#1130]
**Describe the bug**
I want to plot the posterior and prior on the same `pair_plot` matrix. I thought I could do something like `axes=az.pair_plot()` and then `ax.pair_plot(ax=axes)` but get the following error 

```python 
Traceback (most recent call last):
  File "test_model_pyro_torch_jit.py", line 311, in <module>
    coords = {"Mc_dim_1": [0, 1], "Mc_dim_0": [0]}, ax=axes)
  File "/Users/landerson/.local/lib/python3.7/site-packages/arviz-0.7.0-py3.7.egg/arviz/plots/pairplot.py", line 298, in plot_pair
    ax = plot(**pairplot_kwargs)
  File "/Users/landerson/.local/lib/python3.7/site-packages/arviz-0.7.0-py3.7.egg/arviz/plots/backends/matplotlib/pairplot.py", line 174, in plot_pair
    ax[j, i].remove()
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/artist.py", line 137, in remove
    self._remove_method(self)
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 1615, in _remove_ax
    self.delaxes(ax)
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 1031, in delaxes
    self._axstack.remove(ax)
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 106, in remove
    super().remove(self._entry_from_axes(a))
  File "/opt/anaconda3/lib/python3.7/site-packages/matplotlib/figure.py", line 101, in _entry_from_axes
    ind, k = {a: (ind, k) for k, (ind, a) in self._elements}[e]
KeyError: <matplotlib.axes._subplots.AxesSubplot object at 0x14f6a3890>
```

**To Reproduce**
For plotting the posterior on top of the prior in a matrix plot, I tried returning the axes from the prior `axes = plot_pair()` and feeding it to the posterior `plot_pair(ax=axes)` like 
```python
axes = az.plot_pair(pyro_data, kind=['kde'],
                diagonal=True, group='prior', coords = {"Mc_dim_0": [0, 1]}, kde_kwargs={'plot_kwargs':{'alpha':0.1}})
    #import pdb; pdb.set_trace()
az.plot_pair(pyro_data, kind=['scatter', 'kde'],
                diagonal=True, point_estimate='median',
                coords = {"Mc_dim_1": [0, 1], "Mc_dim_0": [0]}, ax=axes)
```
**Expected behavior**
A figure with the posterior samples and prior samples plotted on the same matrix

**Comment by OriolAbril** [comment]
Thanks for reporting the issue, could you share also what is `pyro_data`? Is ti already an InferenceData object? Two different datasets? If it is inference data, what does `pyro_data.posterior` and `pyro_data.prior` print?

**Comment by andersdot** [comment]
Ah yes, it is an InferenceData object of a single dataset, which I created with 
```python
nuts_kernel = NUTS(objective.logjoint, jit_compile=True, ignore_jit_warnings=False)
mcmc = MCMC(nuts_kernel, num_samples=50, warmup_steps=1, num_chains=1)
mcmc.run()
posterior_samples = mcmc.get_samples()
posterior_predictive = Predictive(objective.logjoint, posterior_samples).get_samples()
prior = Predictive(objective.logjoint, num_samples=1000).get_samples()
pyro_data = az.from_pyro(
    mcmc,
    prior=prior,
    posterior_predictive=posterior_predictive)
```

pyro_data.posterior prints
```
<xarray.Dataset>
Dimensions:   (Mc_dim_0: 1, Mc_dim_1: 2, chain: 1, draw: 50)
Coordinates:
  * chain     (chain) int64 0
  * draw      (draw) int64 0 1 2 3 4 5 6 7 8 9 ... 40 41 42 43 44 45 46 47 48 49
  * Mc_dim_0  (Mc_dim_0) int64 0
  * Mc_dim_1  (Mc_dim_1) int64 0 1
Data variables:
    A         (chain, draw) float64 0.2961 0.2429 0.1818 ... 0.6348 0.6414
    d         (chain, draw) float64 0.6848 0.9266 1.846 ... 2.635 2.591 2.527
    Mc        (chain, draw, Mc_dim_0, Mc_dim_1) float64 -0.3176 1.638 ... -1.463
Attributes:
    created_at:                 2020-03-31T17:05:09.827886
    arviz_version:              0.7.0
    inference_library:          pyro
    inference_library_version:  1.2.1 <xarray.Dataset>
```
and pyro_data.prior prints
```
Dimensions:   (Mc_dim_0: 2, chain: 1, draw: 1000)
Coordinates:
  * chain     (chain) int64 0
  * draw      (draw) int64 0 1 2 3 4 5 6 7 8 ... 992 993 994 995 996 997 998 999
  * Mc_dim_0  (Mc_dim_0) int64 0 1
Data variables:
    A         (chain, draw) float64 1.83 1.681 0.7271 ... 1.091 0.3871 0.6304
    d         (chain, draw) float64 1.789 1.34 1.584 ... 0.4282 1.133 0.3592
    Mc        (chain, draw, Mc_dim_0) float64 -0.312 -0.4049 ... -0.3996 -0.535
Attributes:
    created_at:                 2020-03-31T17:05:10.050203
    arviz_version:              0.7.0
    inference_library:          pyro
    inference_library_version:  1.2.1
```

**Comment by OriolAbril** [comment]
I think this is due to trying to call `axes.remove()` multiple times. It should be fixed with something like:

```
if ax.get_figure() is not None:
    ax.remove()
```

as opposed to calling remove straight away as it is done now. I'll try to send a PR whenever I have time, if someone has time before I start the PR go for it.

**Comment by andersdot** [comment]
Which file is the `ax.remove()` calls in?

**Comment by OriolAbril** [comment]
I found 3 calls, all of them should be updated:
* https://github.com/arviz-devs/arviz/blob/master/arviz/plots/backends/matplotlib/pairplot.py#L101
* https://github.com/arviz-devs/arviz/blob/master/arviz/plots/backends/matplotlib/pairplot.py#L174
* https://github.com/arviz-devs/arviz/blob/master/arviz/plots/backends/matplotlib/pairplot.py#L183
