### ISSUE TITLE
Subprocess error for any arviz plot, pymc3 context

### ISSUE THREAD

**Issue by rlloretb** [arviz-devs/arviz#1238]
**Describe the bug**
I cannot plot any plot which involves arviz (pymc3 context)

**To Reproduce**
az.plot_trace(trace)
Traceback (most recent call last):

  File "<ipython-input-4-f1462efd3db0>", line 1, in <module>
    az.plot_trace(trace)

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/arviz/plots/traceplot.py", line 300, in plot_trace
    plot = get_plotting_function("plot_trace", "traceplot", backend)

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/arviz/plots/plot_utils.py", line 605, in get_plotting_function
    backend=backend, plot_module=plot_module

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import

  File "<frozen importlib._bootstrap>", line 983, in _find_and_load

  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 728, in exec_module

  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/arviz/plots/backends/matplotlib/__init__.py", line 43, in <module>
    from .ppcplot import plot_ppc

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/arviz/plots/backends/matplotlib/ppcplot.py", line 4, in <module>
    from matplotlib import animation, get_backend

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 737, in <module>
    class ImageMagickWriter(ImageMagickBase, MovieWriter):

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 120, in wrapper
    if writerClass.isAvailable():

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 730, in isAvailable
    return super().isAvailable()

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 427, in isAvailable
    return shutil.which(cls.bin_path()) is not None

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 724, in bin_path
    binpath = mpl._get_executable_info('magick').executable

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/__init__.py", line 385, in _get_executable_info
    return impl([path, "--version"], r"^Version: ImageMagick (\S*)")

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/__init__.py", line 330, in impl
    raise _cpe

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/__init__.py", line 325, in impl
    universal_newlines=True, errors="replace")

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)

CalledProcessError: Command '['convert', '--version']' returned non-zero exit status 255.

**Expected behavior**
To plot the trace, the posterior...

**Additional context**
arviz: 0.8.3
pymc3: 3.8
python 3.7.7
MacOS Mojave

**Comment by OriolAbril** [comment]
Hi, thanks for reporting.

From the traceback it looks like there is some issue with imports. Could you try executing:

    from matplotlib import animation, get_backend

I think it will raise basically the same error and therefore identify this line as the culprit. 

If this were the issue, the solution would be to move this import to runtime and only if plot_ppc and animated so we'll be able to make a PR and fix this. In the meantime, you can try to either fix this matplotlib imoort issue or use bokeh backend.

**Comment by rlloretb** [comment]
Same error!

from matplotlib import animation, get_backend
Traceback (most recent call last):

  File "<ipython-input-5-147c33e5e58b>", line 1, in <module>
    from matplotlib import animation, get_backend

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 737, in <module>
    class ImageMagickWriter(ImageMagickBase, MovieWriter):

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 120, in wrapper
    if writerClass.isAvailable():

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 730, in isAvailable
    return super().isAvailable()

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 427, in isAvailable
    return shutil.which(cls.bin_path()) is not None

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/animation.py", line 724, in bin_path
    binpath = mpl._get_executable_info('magick').executable

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/__init__.py", line 385, in _get_executable_info
    return impl([path, "--version"], r"^Version: ImageMagick (\S*)")

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/__init__.py", line 330, in impl
    raise _cpe

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/site-packages/matplotlib/__init__.py", line 325, in impl
    universal_newlines=True, errors="replace")

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout

  File "/Users/lloretroger/opt/miniconda3/envs/default/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)

CalledProcessError: Command '['convert', '--version']' returned non-zero exit status 255.

**Comment by rlloretb** [comment]
The problem is importing _animation_. The other one works well.

**Comment by rlloretb** [comment]
Problem solved by installing matplotlib 3.2.1
