### ISSUE TITLE
import pymc3 throws an error   'Dataset' has no attribute 'unify_chunks'

### ISSUE THREAD

**Issue by zh-12345** [arviz-devs/arviz#1425]
when i import import pymcs .it occurred an error that   unify_chunks = _extend_xr_method(xr.Dataset.unify_chunks)
AttributeError: type object 'Dataset' has no attribute 'unify_chunks' 

Traceback (most recent call last):
  File "E:/yanyanyanyan/knowledgegraph/BYESIAN_TEST/1013test.py", line 4, in <module>
    import pymc3 as pm
  File "D:\anadota\lib\site-packages\pymc3\__init__.py", line 41, in <module>
    from .distributions import *
  File "D:\anadota\lib\site-packages\pymc3\distributions\__init__.py", line 15, in <module>
    from . import timeseries
  File "D:\anadota\lib\site-packages\pymc3\distributions\timeseries.py", line 22, in <module>
    from pymc3.util import get_variable_name
  File "D:\anadota\lib\site-packages\pymc3\util.py", line 20, in <module>
    import arviz
  File "D:\anadota\lib\site-packages\arviz\__init__.py", line 16, in <module>
    from .data import *
  File "D:\anadota\lib\site-packages\arviz\data\__init__.py", line 3, in <module>
    from .converters import convert_to_dataset, convert_to_inference_data
  File "D:\anadota\lib\site-packages\arviz\data\converters.py", line 6, in <module>
    from .inference_data import InferenceData
  File "D:\anadota\lib\site-packages\arviz\data\inference_data.py", line 52, in <module>
    class InferenceData:
  File "D:\anadota\lib\site-packages\arviz\data\inference_data.py", line 859, in InferenceData
    unify_chunks = _extend_xr_method(xr.Dataset.unify_chunks)
AttributeError: type object 'Dataset' has no attribute 'unify_chunks'

Process finished with exit code 1

 i am looking forward your reply and  help.

I Viewed  my installation directory
xarray==0.16.1
typing-extensions==3.7.4.2
Theano==1.0.5
arviz==0.10.0

**Comment by zh-12345** [comment]
help ! help ! help!

**Comment by OriolAbril** [comment]
Have you tried calling `unify_chunks` on a xarray Dataset? I am not sure which one is the first xarray version with the method, but 0.16.1 must have it, even if dask is not installed (in which case it does nothing, see source: https://github.com/pydata/xarray/blob/master/xarray/core/dataset.py#L5797). 

Could it be that Python is actually importing an old xarray version instead of 0.16.1 like it should?

**Comment by zh-12345** [comment]
Thank you for your reply.I have solved the problem .I tried to uninstall the the package of "xarray and pymc3",and reinstall xarray 0.16.0. .I don't know why, but luckily it worked out.
