### ISSUE TITLE
plot_trace assumes specific dimensions ordering for divergences

### ISSUE THREAD

**Issue by sethaxen** [arviz-devs/arviz#2150]
**Describe the bug**
If an `InferenceData` contains a `diverging` variable in `sample_stats` that uses the dimension ordering `(draw, chain)` instead of `(chain, draw)`, then `plot_trace` fails.

**To Reproduce**
```python
>>> import arviz as az
>>> import numpy as np
>>> idata = az.from_dict(
...     dict(x=np.random.normal(size=(4, 100, 2))),
...     sample_stats=dict(diverging=np.random.randint(0, 1, size=(4, 100), dtype=bool))
... )
>>> az.plot_trace(idata) # fine
array([[<AxesSubplot:title={'center':'x'}>,
        <AxesSubplot:title={'center':'x'}>]], dtype=object)
>>> idata.posterior['x'] = idata.posterior.x.transpose()
>>> idata.sample_stats['diverging'] = idata.sample_stats.diverging.transpose()
>>> az.plot_trace(idata) # error
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/sethaxen/projects/arviz/arviz/plots/traceplot.py", line 263, in plot_trace
    axes = plot(**trace_plot_args)
  File "/home/sethaxen/projects/arviz/arviz/plots/backends/matplotlib/traceplot.py", line 347, in plot_trace
    div_draws = data.draw.values[chain_divs]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 100 but corresponding boolean dimension is 4
>>> idata = az.InferenceData(posterior=idata.posterior)
>>> az.plot_trace(idata) # fine without diverging
array([[<AxesSubplot:title={'center':'x'}>,
        <AxesSubplot:title={'center':'x'}>]], dtype=object)
```

**Expected behavior**
I expected all calls to `plot_trace` to work above.

**Additional context**
These checks were performed on main.

**Comment by ahartikainen** [comment]
We should add the `.transpose("chain", "draw", ...)` there before stepping into numpy
