### ISSUE TITLE
Import error from pip install

### ISSUE THREAD

**Issue by daeh** [arviz-devs/arviz#457]
I just tried to install with pip and I'm getting this error. Is there something I can try to troubleshoot? (Installing the dev version seems to work so I'm happy to just stick with that if it's more or less stable.)

conda 4.5.12
python '3.7.1 | packaged by conda-forge | (default, Nov 13 2018, 09:50:42) \n[Clang 9.0.0 (clang-900.0.37)]'

```
import arviz as az
Traceback (most recent call last):
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-8-4390affdc1b0>", line 1, in <module>
    import arviz as az
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/arviz/__init__.py", line 23, in <module>
    from .plots import *
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/arviz/plots/__init__.py", line 2, in <module>
    from .autocorrplot import plot_autocorr
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/arviz/plots/autocorrplot.py", line 5, in <module>
    from ..stats.diagnostics import autocorr
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/arviz/stats/__init__.py", line 3, in <module>
    from .stats import *
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/arviz/stats/stats.py", line 12, in <module>
    from .diagnostics import effective_n, gelman_rubin
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/arviz/stats/diagnostics.py", line 10, in <module>
    from ..utils import _var_names
ImportError: cannot import name '_var_names' from 'arviz.utils' (/Users/daeda/anaconda3/envs/rpy/lib/python3.7/site-packages/arviz/utils/__init__.py)
```

Thanks!

**Comment by canyon289** [comment]
Hi Dash
Apologies on the trouble. Could you run this command and tell us the output? Also are you on a mac? I would assume so from Clang but want to double check.

`python -c "import arviz as az; print(az.__version__)"`

I don't have great access to internet right now, but will in ~3 days or so. I'll try recreating to see if I can dive in further for you.

**Comment by to-mi** [comment]
For what it's worth, I have the same issue (on mac, using conda). Installing with `pip install arviz` results in `import arviz` failing with that error message (obviously `python -c "import arviz as az; print(az.__version__)"` fails also with that message; conda tells that arviz version would be 0.3.0).

Installing with `pip install --upgrade git+git://github.com/arviz-devs/arviz.git` gives a version where `import arviz` works.

Not sure how helpful, but I did some investigation and found that the files in the directory `python3.7/site-packages/arviz` are different with these two versions.

The working one ( `pip install --upgrade git+git://github.com/arviz-devs/arviz.git`) has files:
`__init__.py	__pycache__	data		plots		stats		tests		utils.py`

The one that doesn't work (`pip install arviz`) has files:
`__init__.py	data		plots		tests		utils.py
__pycache__	lala.py		stats		utils`

Perhaps the extra `utils` directory is a problem?

**Comment by aloctavodia** [comment]
Hi @to-mi and @daeh sorry for the trouble. I think this is my fault, I include the `utils` directory when creating release 0.3. As a workaround you can remove the `utils` directory.

**Comment by aloctavodia** [comment]
Thanks @to-mi  and @daeh for reporting this issue. It should be fixed now.
